# Generated by Django 2.0.6 on 2019-03-17 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Internship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internship_name', models.CharField(max_length=200)),
                ('company_name', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=200)),
                ('date_posted', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_name', models.CharField(max_length=200)),
                ('company_name', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=200)),
                ('date_posted', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=40)),
                ('user_email', models.EmailField(max_length=40)),
                ('suggestion', models.TextField()),
            ],
        ),
    ]
