# Generated by Django 2.0.6 on 2019-04-27 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_professor_professorstudent_student'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Date',
        ),
        migrations.AddField(
            model_name='professor',
            name='title',
            field=models.CharField(default='Dr. ', max_length=10),
        ),
    ]
